go back only a month

diff --git a/knife b/knife
--- a/knife
+++ b/knife
@@ -38,12 +38,12 @@ function find_latest_snapshot() {
     local type="$1"
     local current="$(date +%Y-%m-01)"
     local tmp=$(mktemp)
-    while [ true ]; do
+    for _ in 1 2; do
         local q=$(date -d "$current" +"year=%Y&month=%m")
         if curl -fs "https://snapshot-cloudflare.debian.org/archive/debian/?$q" | grep -ohE "([0-9]+T[0-9]+Z)" > $tmp; then
             break
         fi
-        echo "Could not find snapshot at $current"
+        echo "Could not find snapshot at $current, going back a month" >&2
         # go back 1 month
         current="$(date -d "$current -1 month" +%Y-%m-01)"
     done
